# Generated by Django 4.2.1 on 2023-06-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voucherotp_voucher_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='balance',
            new_name='amount',
        ),
    ]
