# Generated by Django 4.2.1 on 2023-06-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_balance_voucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='otp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voucherotp'),
        ),
    ]
